// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:FCP_ExampleScript.Update")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:FCP_SpriteMeshEditor.Update")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:FlexibleColorPicker.color")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:FlexibleColorPicker.BufferedColor.a")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:FlexibleColorPicker.BufferedColor.b")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:FlexibleColorPicker.BufferedColor.g")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:FlexibleColorPicker.BufferedColor.h")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:FlexibleColorPicker.BufferedColor.r")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:FlexibleColorPicker.BufferedColor.s")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:FlexibleColorPicker.BufferedColor.v")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:BodyController.lastRotatePositionQueue")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:BodyController.lastVelocityQueue")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:GameController.bodyPieceObjects")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:GameController.bodyPieces")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GameController.AlignAll")]
[assembly: SuppressMessage("Style", "IDE0054:Use '--' operator", Justification = "<Pending>", Scope = "member", Target = "~M:GameController.AddBodyPieceHelper(UnityEngine.Vector3,UnityEngine.Vector3)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:PlayerController.lastRotatePositionQueue")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:PlayerController.lastVelocityQueue")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:PlayerController.velocity")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GameController.SpawnLocation~UnityEngine.Vector3")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:GameController.AlignAll")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.GetGradientMode(FlexibleColorPicker.PickerType)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.GetValue(FlexibleColorPicker.MainPickingMode)~UnityEngine.Vector2")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.GetValue1D(FlexibleColorPicker.PickerType)~System.Single")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.PickColor(FlexibleColorPicker.BufferedColor,FlexibleColorPicker.PickerType,UnityEngine.Vector2)~FlexibleColorPicker.BufferedColor")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.PickColor1D(FlexibleColorPicker.BufferedColor,FlexibleColorPicker.PickerType,System.Single)~FlexibleColorPicker.BufferedColor")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.PickColorMain(FlexibleColorPicker.BufferedColor,FlexibleColorPicker.MainPickingMode,UnityEngine.Vector2)~FlexibleColorPicker.BufferedColor")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.SeperateMaterials")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.OnEnable")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.Start")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.Update")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.IsAlphaType(FlexibleColorPicker.PickerType)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.IsPreviewType(FlexibleColorPicker.PickerType)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.GetNormWorldSpace(UnityEngine.Canvas,UnityEngine.RectTransform,UnityEngine.EventSystems.BaseEventData)~UnityEngine.Vector2")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.GetNormWorldSpace(UnityEngine.Canvas,UnityEngine.RectTransform,UnityEngine.EventSystems.BaseEventData)~UnityEngine.Vector2")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.GetSanitizedHex(System.String,System.Boolean)~System.String")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.GetSanitizedHex(System.String,System.Boolean)~System.String")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.HSVToRGB(System.Single,System.Single,System.Single)~UnityEngine.Color")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.IsPreviewType(FlexibleColorPicker.PickerType)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.MakeModeOptions")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.ParseHex(System.String,UnityEngine.Color)~UnityEngine.Color")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:FlexibleColorPicker.TypeHex(System.String,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:UIDeathScreen.backgroundColor")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:PlayerController.AlignToGrid~UnityEngine.Vector3")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:PlayerController.AlignToGrid~UnityEngine.Vector3")]
